env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - 'plugin:react-hooks/recommended'
  - standard
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
plugins:
  - react
rules:
  semi: ['error', 'always']
  comma-dangle: ['error', 'only-multiline']
  quotes: ['error', 'single', { 'allowTemplateLiterals': true }]
